### ISSUE TITLE
V2.0.0

### ISSUE THREAD

**Issue by boljen** [boljen/node-digital-ocean-api#2]
- Implement all methods
- Unit-test all methods
- Refactor architecture
- Write documentation.

**Comment by cmndrsp0ck** [comment]
Hi there, any updates as to when domain and domain record methods will be implemented?

**Comment by boljen** [comment]
I'm implementing them and the SSH methods as we speak. I'm pleasantly surprised that the API still seems to work since the last time I worked on this package (last commit)

**Comment by cmndrsp0ck** [comment]
lol. I'm definitely glad it does too. Thanks!

**Comment by boljen** [comment]
No problem. I pushed the 0.3.0 package to npm so it should be npm-installable.

**Comment by cmndrsp0ck** [comment]
Sweet! thanks again!

**Comment by boljen** [comment]
I hope you're not using this anymore :)

**Comment by boljen** [comment]
Closing this because the package is unmaintained.
