### ISSUE TITLE
Issue with create domain record

### ISSUE THREAD

**Issue by x5engine** [boljen/node-digital-ocean-api#4]
Hi @boljen,

I have this and can't run the function creaRecord because it throws this error

``````
TypeError: undefined is not a function
W20160816-03:50:47.945(0)? (STDERR)     at /home/ubuntu/workspace/main/node_modules/digital-ocean-api/lib/api.js:149:7
W20160816-03:50:47.945(0)? (STDERR)     at /home/ubuntu/workspace/main/node_modules/digital-ocean-api/lib/api.js:55:14
W20160816-03:50:47.945(0)? (STDERR)     at Request._callback (/home/ubuntu/workspace/main/node_modules/digital-ocean-api/lib/request.js:23:5)
W20160816-03:50:47.945(0)? (STDERR)     at Request.self.callback (/home/ubuntu/workspace/main/node_modules/digital-ocean-api/node_modules/request/request.js:187:22)
W20160816-03:50:47.945(0)? (STDERR)     at Request.emit (events.js:98:17)
W20160816-03:50:47.946(0)? (STDERR)     at Request.<anonymous> (/home/ubuntu/workspace/main/node_modules/digital-ocean-api/node_modules/request/request.js:1044:10)
W20160816-03:50:47.946(0)? (STDERR)     at Request.emit (events.js:95:17)
W20160816-03:50:47.946(0)? (STDERR)     at IncomingMessage.<anonymous> (/home/ubuntu/workspace/main/node_modules/digital-ocean-api/node_modules/request/request.js:965:12)
W20160816-03:50:47.946(0)? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20160816-03:50:47.947(0)? (STDERR)     at _stream_readable.js:944:16
W20160816-03:50:47.947(0)? (STDERR)     at process._tickCallback (node.js:458:13)
=> Exited with code: 8         ```

thanks for the great work and your help :)
``````

**Comment by boljen** [comment]
Could it be that you didn't provide a valid callback as the third argument? The method needs 3 arguments and the last one should be a callable function. I followed the stack trace and I suspect this is what caused it. 

This is the method: https://github.com/boljen/node-digital-ocean-api/blob/master/lib/api.js#L307 .
This is where it throws: https://github.com/boljen/node-digital-ocean-api/blob/master/lib/api.js#L149 .

If this isn't what caused your problem, then please provide me with a code sample that doesn't work and I'll attempt to fix it. If it does fix your problem, then blame me for the lack of documentation and unconventional function signature.

**Comment by x5engine** [comment]
Hello @boljen thanks for the reply,
may be I forgot the third argument because I gave it only two

like this

```
var recordData = {
              "type": "A",
              "name":UniqueName,
              "data": theIP,
              "priority": null,
              "port": null,
              "weight": null
            };
          api.createDomainRecord(recordData,(error, info) => {
```

**Comment by boljen** [comment]
If I recall correctly, you must provide the domain **ID** as the first argument. Could you try this and let me know if it works? Thanks

**Comment by x5engine** [comment]
I just followed the api docs
here https://developers.digitalocean.com/documentation/v2/#create-a-new-domain-record

and it only have one argument which is an object

```
{
  "type": "A",
  "name": "www",
  "data": "162.10.66.0",
  "priority": null,
  "port": null,
  "weight": null
}
```

I am wrong on something?

**Comment by boljen** [comment]
Those are in fact the arguments for the domain record. However, domain records are domain-specific. The digital ocean API requires you to specify the domain inside the endpoint URI;

```
To create a new record to a domain, send a POST request to /v2/domains/$DOMAIN_NAME/records.
```

You can see this in action here; https://github.com/boljen/node-digital-ocean-api/blob/master/lib/api.js#L307

I'm not sure whether you must provide the ID or the actual domain name.
