### ISSUE TITLE
Unhandled error causing app shutdown when using 'includeAll'

### ISSUE THREAD

**Issue by happyrobotgames** [boljen/node-digital-ocean-api#5]
Seems like it's possible for digital ocean to return a body without a 'meta' field. This doesn't cause an issue normally, however if includeAll is specified, it results in a call to getAllPages. This in turn reads 'body.meta.total' without checking if body.meta defined, and generates an error that (as far as I can tell) is not possible for the user to handle. As a result, app shuts down. Guessing simplest solution is a try/catch in the request callback.

**Comment by boljen** [comment]
Thanks for submitting, been a bit busy lately, I'll see when I can fix it

**Comment by boljen** [comment]
Woops, looks like I've forgot about this. Sorry!

I've documented that this library isn't maintained anymore but i'd happily accept a pull request if you still need this  😄
